### ISSUE TITLE
Building project with `foreign_stubs` C dependency: header file not found.

### ISSUE THREAD

**Issue by kentookura** [balsoft/opam-nix#58]
I am trying to build [ocaml-fswatch](https://github.com/kandu/ocaml-fswatch) which depends on [fswatch](https://github.com/emcrisostomo/fswatch).
```
{
  inputs = {
    opam-nix.url = "github:tweag/opam-nix";
    ocaml-fswatch.url = "github:kentookura/ocaml-fswatch";
    ocaml-fswatch.flake = false;
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.follows = "opam-nix/nixpkgs";
  };
  outputs = { self, ocaml-fswatch, flake-utils, opam-nix, nixpkgs }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system}.extend overlay;
        on = opam-nix.lib.${system};
        localPackagesQuery = builtins.mapAttrs (_: pkgs.lib.last)
          (on.listRepo (on.makeOpamRepo ./.));
        devPackagesQuery = {
          ocaml-lsp-server = "*";
          ocamlformat = "*";
          #fswatch = "*";
          #libfswatch = "*";
        };

        query = devPackagesQuery // { ocaml-base-compiler = "*"; };
        libfswatch = pkgs.stdenv.mkDerivation ({
          name = "libfswatch";
          src = pkgs.fetchgit {
            url = "https://github.com/emcrisostomo/fswatch";
            sha256 = "c5Thf/uEHw8aByemG/GxhPH++vz9EqE6pAu40OEvBOM=";
            fetchSubmodules = true;
          };
          nativeBuildInputs = with pkgs; [ clang cmake ];
          buildPhase = "make";
          installPhase = ''
            make install
          '';
        });
        overlay = self: super: {
          fswatch =
            super.fswatch.overrideAttrs (_: { buildInputs = [ libfswatch ]; });
        };
        scope = on.buildDuneProject { } "fswatch" ocaml-fswatch query;
        scope' = scope.overrideScope' overlay;
        main = scope'.fswatch;
        devPackages = builtins.attrValues
          (pkgs.lib.getAttrs (builtins.attrNames devPackagesQuery) scope');
        packages =
          pkgs.lib.getAttrs (builtins.attrNames localPackagesQuery) scope';

      in {
        packages = packages // {
          libfswatch = libfswatch;
          default = main;
        };
        devShells.default = pkgs.mkShell {
          inputsFrom = builtins.attrValues packages;
          buildInputs = devPackages;
        };
      });
}
```
This fails:
```
...
fswatch-dev> File "fswatch/src/dune", line 9, characters 9-13:
fswatch-dev> 9 |   (names stub)))
fswatch-dev>              ^^^^
fswatch-dev> (cd _build/default/fswatch/src && /nix/store/nlgyw2fv0cm8rkz8qm1jyw78vyif1bl9-gcc-wrapper-12.2.0/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -fdiagnostics-color=always -g -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/threads -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/unix -o stub.o -c stub.c)
fswatch-dev> stub.c:11:10: fatal error: libfswatch.h: No such file or directory
fswatch-dev>    11 | #include <libfswatch.h>
fswatch-dev>       |          ^~~~~~~~~~~~~~
fswatch-dev> compilation terminated.
error: builder for '/nix/store/4f8jr0dips13v5vxma9bascqsggjm4xp-fswatch-dev.drv' failed with exit code 1;
       last 10 log lines:
       > building
       > File "fswatch/src/dune", line 9, characters 9-13:
       > 9 |   (names stub)))
       >              ^^^^
       > (cd _build/default/fswatch/src && /nix/store/nlgyw2fv0cm8rkz8qm1jyw78vyif1bl9-gcc-wrapper-12.2.0/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -fdiagnostics-color=always -g -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/threads -I /nix/store/gksszmxms1n9vhvz6fcx4ls7kaz5nm6n-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/unix -o stub.o -c stub.c)
       > stub.c:11:10: fatal error: libfswatch.h: No such file or directory
       >    11 | #include <libfswatch.h>
       >       |          ^~~~~~~~~~~~~~
       > compilation terminated.
       >
```
So the problem lies with the following command:
```
/nix/store/...-gcc-wrapper-12.2.0/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -fdiagnostics-color=always -g -I /nix/store/...-ocaml-base-compiler-5.1.0_rc3/lib/ocaml -I /nix/store/...-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/threads -I /nix/store/...-ocaml-base-compiler-5.1.0_rc3/lib/ocaml/unix -o stub.o -c stub.c
```
Am I passing the `buildInputs` correctly to `opam-nix`?

**Comment by balsoft** [comment]
Fixed!

**Comment by kentookura** [comment]
Thanks! Could you provide a flake that builds? Haven't managed to modify mine so that it works... (to be sure, i did run `nix flake update`)

**Comment by balsoft** [comment]
Remove all the overlays. E.g. this should work:
```nix
{
  inputs = {
    opam-nix.url = "github:tweag/opam-nix";
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.follows = "opam-nix/nixpkgs";
  };
  outputs = { self, flake-utils, opam-nix, nixpkgs }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        on = opam-nix.lib.${system};
        localPackagesQuery = builtins.mapAttrs (_: pkgs.lib.last)
          (on.listRepo (on.makeOpamRepo ./.));
        devPackagesQuery = {
          # You can add "development" packages here. They will get added to the devShell automatically.
          ocaml-lsp-server = "*";
          ocamlformat = "*";
        };
        query = devPackagesQuery // {
          ocaml-base-compiler = "*";

          fswatch = "*";
        };
        scope = on.buildOpamProject' { } ./. query;
        overlay = final: prev:
          {
            # You can add overrides here
          };
        scope' = scope.overrideScope' overlay;
        # Packages from devPackagesQuery
        devPackages = builtins.attrValues
          (pkgs.lib.getAttrs (builtins.attrNames devPackagesQuery) scope');
        # Packages in this workspace
        packages =
          pkgs.lib.getAttrs (builtins.attrNames localPackagesQuery) scope';
      in {
        legacyPackages = scope';

        inherit packages;

        ## If you want to have a "default" package which will be built with just `nix build`, do this instead of `inherit packages;`:
        # packages = packages // { default = packages.<your default package>; };

        devShells.default = pkgs.mkShell {
          inputsFrom = builtins.attrValues packages;
          buildInputs = devPackages ++ [
            # You can add packages from nixpkgs here
          ];
        };
      });
}

```

**Comment by kentookura** [comment]
Unfortunately I am still getting the same error running `nix build .#fswatch`.

**Comment by balsoft** [comment]
Ah, your project might require an older version of it. I'll look into it.

**Comment by kentookura** [comment]
Thanks, the default package now builds, which is what I needed, but `fswatch_async` and `fswatch_lwt` still doesn't build.

**Comment by balsoft** [comment]
You can open issues for them if you need them. I'll fix when I have spare time.
